// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDngz2ctZb5cl57dogzX0G5KTH4DTsnghA',
    appId: '1:644615304094:web:cf989c6ad9065323211c8f',
    messagingSenderId: '644615304094',
    projectId: 'movieapp-c9767',
    authDomain: 'movieapp-c9767.firebaseapp.com',
    databaseURL: 'https://movieapp-c9767-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-c9767.appspot.com',
    measurementId: 'G-0ST4Q2J49Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHyDA01gvMdUcZMXAXCjixb-beu2xVQNY',
    appId: '1:644615304094:android:b9eb4a7fcecd2c99211c8f',
    messagingSenderId: '644615304094',
    projectId: 'movieapp-c9767',
    databaseURL: 'https://movieapp-c9767-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-c9767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhAJaj2Vi1LVYeRPHUFjYcHY4p8Wd9a0',
    appId: '1:644615304094:ios:ad3ba1a5cbb50e64211c8f',
    messagingSenderId: '644615304094',
    projectId: 'movieapp-c9767',
    databaseURL: 'https://movieapp-c9767-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-c9767.appspot.com',
    iosBundleId: 'com.example.untitled10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdhAJaj2Vi1LVYeRPHUFjYcHY4p8Wd9a0',
    appId: '1:644615304094:ios:5c527613026440b0211c8f',
    messagingSenderId: '644615304094',
    projectId: 'movieapp-c9767',
    databaseURL: 'https://movieapp-c9767-default-rtdb.firebaseio.com',
    storageBucket: 'movieapp-c9767.appspot.com',
    iosBundleId: 'com.example.untitled10.RunnerTests',
  );
}
